CREATE TABLE IF NOT EXISTS rooms (
  id VARCHAR(5) PRIMARY KEY,
  board VARCHAR(9) NOT NULL DEFAULT '---------',
  turn CHAR(1) NOT NULL DEFAULT 'X',
  player_x TINYINT(1) NOT NULL DEFAULT 0,
  player_o TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(10) NOT NULL DEFAULT 'waiting',
  winner VARCHAR(5) DEFAULT NULL,
  win_line VARCHAR(10) DEFAULT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
